### ISSUE TITLE
I got wrong message...

### ISSUE THREAD

**Issue by xw2003318** [julienj/phpOlap#1]
hi Julienj, 
Rencently, I'm using your phpOlap to connect SSAS. But failed... See following picture
I opened php SOAP extend, and also added Symfony to vendor folder. But still doesn't work...
Could you please help me out here? BTW, I saw your website(phpolap.org) is closed. Is there any place, i can get more samples or documents
thank you very much!
![default](https://cloud.githubusercontent.com/assets/10723143/5916673/9b567cf2-a64e-11e4-86f4-40393b46f6dd.PNG)
here is my wrong message

Fatal error: Uncaught exception 'phpOlap\Xmla\Connection\Adaptator\AdaptatorException' with message 'SOAP error : no response' in D:\WWW\test\src\phpOlap\Xmla\Connection\Adaptator\SoapAdaptator.php:140 Stack trace: #0 D:\WWW\test\src\phpOlap\Xmla\Connection\Adaptator\SoapAdaptator.php(86): phpOlap\Xmla\Connection\Adaptator\SoapAdaptator->call(Object(DOMDocument), 'Discover') #1 D:\WWW\test\src\phpOlap\Xmla\Connection\Connection.php(139): phpOlap\Xmla\Connection\Adaptator\SoapAdaptator->discover('MDSCHEMA_CUBES', Array, Array) #2 D:\WWW\test\src\phpOlap\Xmla\Connection\Connection.php(149): phpOlap\Xmla\Connection\Connection->findCubes(NULL, Array) #3 D:\WWW\test\src\index.php(27): phpOlap\Xmla\Connection\Connection->findOneCube(NULL, Array) #4 {main} thrown in D:\WWW\test\src\phpOlap\Xmla\Connection\Adaptator\SoapAdaptator.php on line 140

and here is my code
<?php
require_once '../autoload.php';
use phpOlap\Xmla\Connection\Connection;
use phpOlap\Xmla\Connection\Adaptator\SoapAdaptator;

// for Microsoft SQL Server Analysis Services
*/
$connection = new Connection(
    new SoapAdaptator('http://192.1681.1.108/olap/msmdpump.dll', 'administrator', '1qaz@WSX'),
    array(
        'DataSourceInfo' => null,
        'CatalogName' => 'CaseSSAS'
        )
);

$cube = $connection->findOneCube(null, array('CUBE_NAME' => 'Case'));
?>

<p><label>Cube :<?php echo $cube->getName() ?></label></p>

thank you very much!

**Comment by xw2003318** [comment]
BTW, I use php5.5n and added SOAP extension, also included Symfony2.0 into vendor folder. My SSAS link can be used by SSAS or Excel, so i think link is no problem. And I check SOAP make a test, it seems well. So, is there any thing i lost? Or could you please send me more sample or docments about , except phpolap or olap4php, is there any way I can connect SSAS via PHP? this issuce torments me many days.... All my need is a easy way to connect to ssas via php and get data show on webpage...

**Comment by xw2003318** [comment]
and I even tried add port number for the link(http://192.1681.1.108:2725/olap/msmdpump.dll' or http://192.1681.1.108:2383/olap/msmdpump.dll'), same issue...
It seems the link doesn't work in Connection(). But it works in SSAS and Excel...

**Comment by xw2003318** [comment]
after checking, checking, checking... I found out the problems... it's my fault ... sorry. I think it is because i install Apche and IIS on same computer, and even i set link with ip, there must be some conflict here. So when i changed IP to 'Localhost', it works...
http://localhost/olap/msmdpump.dll
thank you!
